### ISSUE TITLE
No active menu?

### ISSUE THREAD

**Issue by cadilhac** [CSharpDesignPro/Navigation-Drawer-Sidebar-Menu-in-WPF#1]
Very nice.

Since the menu entries are toggle buttons, it's a pity that they are not displayed with a different background color when they are clicked/toggled. With the notion of active menu, the sample would be complete for people to use.

**Comment by CSharpDesignPro** [comment]
Hi cadilhac,

Thanks for the appreciation. I think you've failed to observe the toggle button properly. There is a shadow effect around the toggle button when it is clicked /toggled. 

`<ImageBrush  x:Key="tb_mouse_over"
                        ImageSource="Assets/tgBtn_MouseOver.png"/>`

You are free to edit and change the background color in the provided source code.

`<ToggleButton.Background>
            <SolidColorBrush Color="DarkGray"/>
 </ToggleButton.Background>`

This repository is not an independent project but rather a supplement /companion to the YouTube video tutorial series. I need to maintain the code, as explained in the video tutorial. I hope that helps!

**Comment by cadilhac** [comment]
There is definitely no effect when toggled. Are you confusing it with hover? Because the ImageBrush you show me is for hover.

**Comment by CSharpDesignPro** [comment]
@cadilhac 

I can understand your issue. You are expecting me to update the source code with an entirely different design concept, which I think is not possible. Any attempts to change it would make the associated YouTube tutorial irrelevant. The source code provided is "as is". You can always modify the code /design concept to your liking with your expertise.

**Comment by cadilhac** [comment]
I was not expecting anything. I was just mentioning that this would make sense for such a demo/app to have a working toggled state since in the end, this is what people need with such a menu.

**Comment by CSharpDesignPro** [comment]
I'm not qualified enough to determine what exactly people need. Every client has a different software requirements specification. But no worries, if this toggle button does not make any sense to you, then perhaps I could make a video tutorial in the future with an advanced menu design that is ready to use. Thanks for mentioning it. Cheers!

**Comment by cadilhac** [comment]
I don't think this is related to particular client needs. I was just expressing the fact that your sample would be feature complete by adding this very logical feature for a vertical menu that acts like tabs. When you click one entry, it changes the content on the right side and therefore, the active menu should be highlighted. This is an advice, nothing else ;)

**Comment by CSharpDesignPro** [comment]
Thanks for the advice. It's not that I haven't thought about the idea /feature but, that would be beyond the scope of this tutorial. A tabbed layout would need additional code and, that means a longer video with a runtime of 50+ mins. Making this app feature-complete is subjective to the developer. As I mentioned earlier, you are free to modify the code to your requirement.
